version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - AuthServer_DB=AbpUppyUploadService_Identity
      - AbpUppyUploadService_DB=AbpUppyUploadService_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
